//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectumCareerNightBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectumCareerNightBot.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, это команда Directum.
        ///            
        ///35 лет мы создаём решения, которые упрощают электронный документооборот, бизнес-процессы и жизнь в целом.
        ///    
        ///Этот чат-бот был создан специально для Ночи карьеры. С его помощью ты сможешь попасть на собеседование, узнать о направлениях работ в компании, получить мерч и откликнуться на практику.
        ///        .
        /// </summary>
        internal static string BotStartMessage {
            get {
                return ResourceManager.GetString("BotStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать о вакансиях.
        /// </summary>
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 вопросов Directum.
        /// </summary>
        internal static string Directum15Questions {
            get {
                return ResourceManager.GetString("Directum15Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ищи на сцене 3 больших стола Directum:
        ///-  Стол «про разработку».
        ///-  Стол «про тестирование».
        ///-  Стол «про аналитику, маркетинг, внедрение, продажи».
        ///
        ///Группе от 6 человек специалисты рассказывают  о своих направлениях..
        /// </summary>
        internal static string Directum15QuestionsMessage {
            get {
                return ResourceManager.GetString("Directum15QuestionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания Directum в VK.
        /// </summary>
        internal static string DirectumCompanyVK {
            get {
                return ResourceManager.GetString("DirectumCompanyVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенты Directum в VK.
        /// </summary>
        internal static string DirectumStudentsVK {
            get {
                return ResourceManager.GetString("DirectumStudentsVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как удобнее будет поддерживать связь с нашим HR-ом — напиши свои телефон/почту/vk.
        /// </summary>
        internal static string HowToContact {
            get {
                return ResourceManager.GetString("HowToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какое направление тебе интересно?.
        /// </summary>
        internal static string InterestingDirection {
            get {
                return ResourceManager.GetString("InterestingDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давай знакомиться, напиши свои фамилию, имя и отчество.
        /// </summary>
        internal static string IntroduceYourself {
            get {
                return ResourceManager.GetString("IntroduceYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбирай, что тебе интересно!.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться в меню.
        /// </summary>
        internal static string MainMenuButton {
            get {
                return ResourceManager.GetString("MainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркетинг.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже не студент, но хочу в ИТ.
        /// </summary>
        internal static string NotStudentButWantInIT {
            get {
                return ResourceManager.GetString("NotStudentButWantInIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программирование.
        /// </summary>
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответь верно на 5 вопросов и получи подарок от Directum!.
        /// </summary>
        internal static string QuizStartMessage {
            get {
                return ResourceManager.GetString("QuizStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розыгрыш мерча.
        /// </summary>
        internal static string RafflePrizes {
            get {
                return ResourceManager.GetString("RafflePrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи.
        /// </summary>
        internal static string Sails {
            get {
                return ResourceManager.GetString("Sails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старшекурсник с опытом в ИТ, хочу в Directum.
        /// </summary>
        internal static string StudentWithExperience {
            get {
                return ResourceManager.GetString("StudentWithExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи про свой опыт в этом направлении.
        /// </summary>
        internal static string TellAboutChosenDirection {
            get {
                return ResourceManager.GetString("TellAboutChosenDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи о своём опыте в IT, в какой компании работал, на какой должности.
        /// </summary>
        internal static string TellAboutITExpirience {
            get {
                return ResourceManager.GetString("TellAboutITExpirience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи о своём последнем месте работы, опыте.
        /// </summary>
        internal static string TellAboutLastWork {
            get {
                return ResourceManager.GetString("TellAboutLastWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи в какой компании ты сейчас работаешь, на какой должности, если хочешь напиши подробнее про свой опыт.
        /// </summary>
        internal static string TellAboutYourCompany {
            get {
                return ResourceManager.GetString("TellAboutYourCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи какие задачи ты выполняешь на своей должности.
        /// </summary>
        internal static string TellAboutYourCompanyPlace {
            get {
                return ResourceManager.GetString("TellAboutYourCompanyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирование.
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднимайся на сцену. За столом с табличкой **«Мы тебя ждали»** пройдёт твоё собеседование. Представься, чтобы твою анкету нашли и с тобой пообщался нужный специалист..
        /// </summary>
        internal static string ThankYouAlumnus {
            get {
                return ResourceManager.GetString("ThankYouAlumnus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднимайся на сцену. За столом с табличкой **«Мы тебя ждали»** пройдёт твоё собеседование. Представься, чтобы твою анкету нашли и с тобой пообщался нужный специалист..
        /// </summary>
        internal static string ThankYouInIT {
            get {
                return ResourceManager.GetString("ThankYouInIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднимайся на сцену. За столом с табличкой «Мы тебя ждали» тебе расскажут о возможностях в Directum. Представься, чтобы твою анкету нашли и с тобой пообщался нужный специалист..
        /// </summary>
        internal static string ThankYouInITDept {
            get {
                return ResourceManager.GetString("ThankYouInITDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поднимайся на сцену! За столом с табличкой **«Попасть в ИТ»** тебе расскажут о возможностях. Крепись, ты можешь оказаться 30м в очереди на общение. А  пока есть время, и ты уже занял очередь, можешь прогуляться к нашему стенду..
        /// </summary>
        internal static string ThankYouNotStudent {
            get {
                return ResourceManager.GetString("ThankYouNotStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо! Мы передадим твою анкету рекрутеру, в случае положительного решения он свяжется с тобой до **30 апреля**. Не забудь взять трубку с незнакомого номера, если указал телефон предпочтительным способом связи. 
        ///
        ///Если остались вопросы, за правой кулисой на сцене группе от 6 человек Настя расскажет о практике.
        /// </summary>
        internal static string ThankYouPractice {
            get {
                return ResourceManager.GetString("ThankYouPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу на практику!.
        /// </summary>
        internal static string WantToPractice {
            get {
                return ResourceManager.GetString("WantToPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что уже изучал в ИТ? Ответь в свободной форме.
        /// </summary>
        internal static string WhatYouAlreadyLearned {
            get {
                return ResourceManager.GetString("WhatYouAlreadyLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работаю в ИТ-департаменте/отделе.
        /// </summary>
        internal static string WorkerInITDept {
            get {
                return ResourceManager.GetString("WorkerInITDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работаю в ИТ, хочу сменить компанию.
        /// </summary>
        internal static string WorkInITButWantToChangeCompany {
            get {
                return ResourceManager.GetString("WorkInITButWantToChangeCompany", resourceCulture);
            }
        }
    }
}
