//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectumCoffee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectumCoffee.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад ↩️.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет\!👋
        ///*Я бот Random Coffee Directum* 🤖
        ///*Каждую неделю* я буду предлагать тебе встречу с кем\-то из твоих коллег\.
        ///
        ///На Random Coffee ты сможешь\:
        ///🔸 познакомиться с коллегами из разных команд и узнать об их работе\;
        ///🔸 обменяться опытом или пообщаться о личном\;
        ///🔸 найти друлегу или сэнсея, а то и сам помочь кому\-то прокачаться\.
        ///
        ///Для старта *ответь* на несколько вопросов и *прочитай* небольшую инструкцию\.
        ///        .
        /// </summary>
        internal static string BotFirstMeet {
            get {
                return ResourceManager.GetString("BotFirstMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Coffee в Directum\! Раз в неделю я буду предлагать тебе встречу с кем\-то из твоих коллег\. Не откладывай эту возможность в долгий ящик 😉.
        /// </summary>
        internal static string BotStartMessage {
            get {
                return ResourceManager.GetString("BotStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить анкету.
        /// </summary>
        internal static string ChangeInfo {
            get {
                return ResourceManager.GetString("ChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поехали 🚀.
        /// </summary>
        internal static string GoMessage {
            get {
                return ResourceManager.GetString("GoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упс... Твоей анкеты ещё нет.
        /// </summary>
        internal static string InfoNotFound {
            get {
                return ResourceManager.GetString("InfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получилось\! 🥰
        ///
        ///Краткая инструкция\:
        ///🔸 Раз в неделю в этом чате я буду присылать имя коллеги\, с которым тебе предстоит встретиться\.
        ///🔸 Напиши ему или ей в Telegram или в ММ и договорись о времени\. Не откладывай на потом 🙂
        ///🔸 Обычно Random Coffee проходит офлайн\. Но если вы с коллегой живете в разных городах\, можете договориться о встрече в Толке\!.
        /// </summary>
        internal static string MainScenbarioIsDonePart1 {
            get {
                return ResourceManager.GetString("MainScenbarioIsDonePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔸 Коллега не отвечает\? Напиши и я подберу новую пару для встречи\.
        ///🔸 В пятницу я уточню\, как прошла встреча и хочешь ли ты продолжить участие в Random Coffee\.
        ///🔸 Если хочешь отказаться от встреч\, просто напиши мне \/stop\..
        /// </summary>
        internal static string MainScenbarioIsDonePart2 {
            get {
                return ResourceManager.GetString("MainScenbarioIsDonePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хороших встреч\! ☕️.
        /// </summary>
        internal static string MainScenbarioIsDonePart3 {
            get {
                return ResourceManager.GetString("MainScenbarioIsDonePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя анкета.
        /// </summary>
        internal static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ясно, продолжай 🤓.
        /// </summary>
        internal static string OkContinue {
            get {
                return ResourceManager.GetString("OkContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок, жду сообщения.
        /// </summary>
        internal static string OkWait {
            get {
                return ResourceManager.GetString("OkWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Собеседник найден! Это {0}.
        ///
        ///О чём можете пообщаться?
        ///
        ///✅ Увлечения: {1}
        ///
        ///✅ Работа: {2}
        ///
        ///✅ Интересы: {3}
        ///
        ///Скорей пиши в ММ и назначай встречу!.
        /// </summary>
        internal static string PairFoundMessage {
            get {
                return ResourceManager.GetString("PairFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кажется, пока нет свободных людей тебе в пару.
        ///
        ///Но всё равно не отчаивайся! Жди очередное распределение на следующей неделе!
        ///
        ///И помни, чем больше интересов ты пропишешь, тем больше вероятность найти подходящего собеседника..
        /// </summary>
        internal static string PairNotFoundCompletelyMessage {
            get {
                return ResourceManager.GetString("PairNotFoundCompletelyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Пары распределены!✨
        ///
        ///Пока мы не нашли людей с интересами, похожими на твои. 
        ///
        ///Но не отчаивайся! Ты можешь попробовать пообщаться со случайным собеседником..
        /// </summary>
        internal static string PairNotFoundMessage {
            get {
                return ResourceManager.GetString("PairNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить анкету.
        /// </summary>
        internal static string RestartInfo {
            get {
                return ResourceManager.GetString("RestartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рад снова тебя видеть\! Тебе снова будут прилетать приглашения\. Если хочешь, можешь изменить анкету через кнопку \/start\..
        /// </summary>
        internal static string RestartInfoMessage {
            get {
                return ResourceManager.GetString("RestartInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить анкету.
        /// </summary>
        internal static string StopInfo {
            get {
                return ResourceManager.GetString("StopInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грустно, но  я понимаю\. Если захочешь вернуться, то нажми снова \/start\..
        /// </summary>
        internal static string StopInfoMessage {
            get {
                return ResourceManager.GetString("StopInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно\! Хочешь изменить что\-то ещё\?.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧡 Укажи свой *город* — это поможет учесть разницу во времени для разных часовых поясов\..
        /// </summary>
        internal static string YourCity {
            get {
                return ResourceManager.GetString("YourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧡 А теперь — немного *о себе*\: чем ты увлекаешься в свободное время\?.
        /// </summary>
        internal static string YourHobby {
            get {
                return ResourceManager.GetString("YourHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧡 О чем тебе *интересно пообщаться*\?.
        /// </summary>
        internal static string YourInterests {
            get {
                return ResourceManager.GetString("YourInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧡 Как тебя зовут\? Укажи *имя и фамилию*\. Так коллега проще сможет найти тебя в справочнике «Сотрудник» или на блоге\..
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧡 Коротко расскажи о своей *работе*, задачах и проектах\.
        ///В каком направлении ты работаешь\?.
        /// </summary>
        internal static string YourWork {
            get {
                return ResourceManager.GetString("YourWork", resourceCulture);
            }
        }
    }
}
